### ISSUE TITLE
Map License 

### ISSUE THREAD

**Issue by mikemhenry** [ttinies/sc2gameMapRepo#1]
Having a hard time tracking down the license used for the maps, is it okay to redistribute them? Can you point me in the direction of the license for the maps? Especially the official ones from Blizzard.

Thanks!

**Comment by ttinies** [comment]
This is a good to consider the situation.

First, at the bottom of the documentation are references to various map repos -- I talked with each of the map repo owners and obtained their permission to include them in this package.  Some don't have licenses; others don't.  pysc2 uses the same apache 2.0 license.  That's pretty cut and dry.

Previously, I found nothing concrete for Blizzard maps that specifies this repo publication would go against anything Blizzard claims. Nothing in their policies that I could see govern distributing maps, even Blizzard maps -- except unless its done for financial gain or commercial purpose.

In the SC2 map editor, the 'author' is listed as Blizzard, but most maps list the actual creator in the description.  Blizzard's policy is pretty anal about map ownership.  In fact, in the EULA they outright claim 100% ownership of all maps ever created for their games.

* [Blizzard EULA](http://us.blizzard.com/en-us/company/legal/eula)
* [Blizzard Acceptable Use](http://us.blizzard.com/en-us/company/legal/acceptable-use.html)

While the EULA's assertions don't hold water legally speaking, this also isn't worth going to war over. I published this repo to help others, that's it. This is somewhat murky water.  I'll reach out to Blizzard and ask permission. If Blizz objects to our usage, we'll just unpublish this repository from github.

**Comment by ttinies** [comment]
Ticket ID US63604078

**Comment by mikemhenry** [comment]
If we can't redistribute, then we can keep the repo and just have a script
that downloads the maps. That's what a lot of people do to get around the
redistribution limitation.

**Comment by ttinies** [comment]
Lady Game Master Powencis responded.  Besides a mildly entertaining email, she confirmed that maps already provided for free by Blizzard "should be fine" as long as there's no profit for doing so.  She also included another link to a [legal FAQ](http://us.blizzard.com/en-us/company/about/legal-faq.html) that also seems to confirm as much.
